### ISSUE TITLE
Inconsistent showAchievement

### ISSUE THREAD

**Issue by AI-Error-404** [5FB5/gd-achievements#18]
Hi, I'm relatively new to Godot, been using it for less than a year, and am working on a game for steam, I am using your achievement system as per the readme instructions and I have come across an error where, for instance: I set the player to get an achievement at index 0 upon watching the opening cutscene. It worked great on the first pass, however, once the player has already earned that achievement when you load the game up again and watch the cutscene again it gives the player the next achievement in the list. I am using $AchievementSystem.emit_signal("showAchievement", 0) but it seems that when the player gets the achievement it subtracts 1 making index 1 the new index 0.

**Comment by 5FB5** [comment]
Can you make a test project that can reproduce bug? Have you checked Q/A?

**Comment by AI-Error-404** [comment]
yes, ill put together a project now

**Comment by AI-Error-404** [comment]
Issue is solved, no fault of yours or the plugin. I simply misordered my achievements,  $AchievementSystem.getAchievementsAllNames() sorted it right out. in the future could you add a bit of code that allows the getAchievementsAllNames method to return the name as well as its Index within the .JSON?

**Comment by 5FB5** [comment]
I've added printing an achievement index from JSON. Download update from develop branch and let me know if it works
