### ISSUE TITLE
Rework the plugin

### ISSUE THREAD

**Issue by jabsatz** [5FB5/gd-achievements#20]
Hello!

My team and I were looking for a plugin similar to this one, so I tried to download it and run it. Some parts of it were very helpful (specifically all the dealings with .json saving/loading which I always find to be a pain). Unfortunately, some features we wanted were missing, so I added (locally) a couple of things we needed. In the process, I also rewrote a big portion of the plugin, to make some functionalities work more in sync with godot best practices.

I'd be more than happy to make a pull request to show you these changes, and if you agree, to merge and release them as a new version. I understand if you see this as some random guy just trying to get into your plugin, but I don't like to make new plugins to compete with what's already there, so it'd be great if you'd accept this.

Please let me know if this would interest you, and I'll prepare it in a fork and send it your way.

# Features/fixes/refactors made:

- Moved most of the functionality from the "AchievementSystem" node to the "Global" node, except the things related with rendering the notifications
- Moved the "AchievementData" functionality to the "Global" node and deleted "AchievementData".
- Renamed the "Global" component to "AchievementManager" and the "AchievementSystem" node to "AchievementNotifications"
- I also deleted the "getter" functions for each achievement's field, and replaced them with a `getAchievement(id)` function that returns the whole dictionary, since it seemed unnecessary to have so many getters.
-----------
- The "AchievementManager" now has 2 functions to track achievements: `progress_achievement(id, progress)` which increases the progress of a specific achievement, and eventually unlocks it, and `unlock_achievement(id)` which instantly unlocks an achievement
  - From your code it doesn't look like you knew this, but in godot if you have an Autoload, you do not need to use `get_node('/root/AchievementManager').unlock_achievement(id)`, you can simply call `AchievementManager.unlock_achievement(id)`, which is very user friendly
  - These functions emit a new signal `achievement_unlocked(achievement)`. The "AchievementNotifications" will automatically receive these and display them on-screen.
- The "AchievementNotifications" can now stack in any direction (before, they only stacked down). This can be set by a property in the editor.
- The shape of "achievements.json" is changed, as there were some typos and the "progress" didn't make sense to be at 0 if the achievement doesn't exist. If there is progress, there will also be a "goal". The progress will increase when using `AchievementManager.progress_achievement()` until it reaches the goal, then it'll emit the signal to show the achievement. Now it looks like this:
```
{
  "infinite_suffering": {
    "name": "Infinite Suffering",
    "description": "Die 5 times",
    "is_secret": false,
    "goal": 5,
    "progress": 0,
    "icon_path": "res://gd-achievements/achievement_test.png",
    "achieved": false
  },
  "headache": {
    "name": "You'll have a headache in the morning",
    "description": "Kill 4 monsters with a single explosion",
    "is_secret": false,
    "icon_path": "res://gd-achievements/achievement_test.png",
    "achieved": false
  }
}
```

The main issue all of these changes have is that they would NOT be backwards compatible. If you're interested in merging this, I will find a way to accomodate for backwards compatibility.

**Comment by 5FB5** [comment]
Hello! It's very nice that you appreciated this plugin and use it in your projects (as I understand). In fact, I support the opportunities offered by the idea of Open Source, so I will be glad if you make changes that expand the required functionality, as I made this project for my own needs and with a minimum set of functionality. You can send a pull request, but I don't have time to look into it all yet, so I'll be able to accept it a bit later. It would also be great if you have extended documentation on your features (updated README)

**Comment by jabsatz** [comment]
Excellent! Thank you for the quick response and good disposition 😄!

I'll make time over the weekend to make the fork, clean it up and send it your way!
