### ISSUE TITLE
Achievements doesn't work on Android

### ISSUE THREAD

**Issue by Dark8Ghost** [5FB5/gd-achievements#24]
**Describe the bug**
Achievements does not work on android devices. It's look like it doesn't even compile with the game as there is literally no trace of it in the exported version.

**To Reproduce**
1. Setup all the achievements.
2. Export the game to android (One-Click Deploy or normal APK)
3. Try to get the achievements or read the achievements through the android device (Nothing shows!)

**Expected behavior**
To get the achievements on the android mobile device similar to how I get it on PC.

**Version of Godot**
Stable 3.5.2

**Additional context**
The plugin works perfectly on the PC but not on android devices.

**Comment by 5FB5** [comment]
Interesting issue, but I haven't any Android device to test it, sorry :(

**Comment by Dark8Ghost** [comment]
I used [Genymotion ](https://www.genymotion.com/download/ ) to test it with along with an actual android device. Can I help with anything regarding this issue?

**Comment by 5FB5** [comment]
> I used [Genymotion ](https://www.genymotion.com/download/) to test it with along with an actual android device. Can I help with anything regarding this issue?

Ok, I'll try to test it on emulator, but now I really don't have any time for it, 'cause work and other stuff. I will check it later. Or if you are programmer, then feel free to send a PR into this repo

**Comment by Dark8Ghost** [comment]
I doubt that I can fix it on my own, but if something happens, I will sure post it here. Best of luck and thank you.

**Comment by Dark8Ghost** [comment]
Alright, so I found a solution to this problem. As far as I understand, even though Godot export all resources used in the project for PC in default, it does not do it for Android. Therefore to fix this, you need to go to **Export => Click on Android Presets => Go to Resources tab, and set ***.json** as filter for resources to export.**

This fixed my problem and now your plugin works perfectly on android as well. Cheers!
![image](https://user-images.githubusercontent.com/100872264/226140382-2b7ff1b6-1299-485f-be6b-022390976b73.png)

**Comment by 5FB5** [comment]
> Alright, so I found a solution to this problem. As far as I understand, even though Godot export all resources used in the project for PC in default, it does not do it for Android. Therefore to fix this, you need to go to *_Export => Click on Android Presets => Go to Resources tab, and set _**.json** as filter for resources to export.__
> 
> This fixed my problem and now your plugin works perfectly on android as well. Cheers! ![image](https://user-images.githubusercontent.com/100872264/226140382-2b7ff1b6-1299-485f-be6b-022390976b73.png)

Ok, I add it to README

**Comment by 5FB5** [comment]
Added in Q/A section
